# Generated by Django 5.2.4 on 2025-08-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_de_livraison', to='fournisseurs.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('bon_de_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='stock.bondelivraison')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('bons_de_livraison', models.ManyToManyField(related_name='factures', to='stock.bondelivraison')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fournisseurs.fournisseur')),
            ],
        ),
    ]
