# Generated by Django 4.1.13 on 2025-08-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_article_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='bons_de_livraison',
        ),
    ]
