# Generated by Django 4.1.13 on 2025-08-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('stock', '0003_remove_facture_bons_de_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondelivraison',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_de_livraison', to='fournisseurs.fournisseur'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='fournisseurs.fournisseur'),
        ),
    ]
