# Generated by Django 4.1.13 on 2025-08-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('stock', '0004_alter_bondelivraison_fournisseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('BON', 'Bon de livraison'), ('FACTURE', 'Facture')], default='BON', max_length=10)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='fournisseurs.fournisseur')),
            ],
        ),
        migrations.RemoveField(
            model_name='facture',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='bon_de_livraison',
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BonDeLivraison',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.AddField(
            model_name='article',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='stock.document'),
        ),
    ]
