# Generated by Django 4.1.13 on 2025-08-07 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CONFIRMED', 'Confirmé'), ('PAID', 'Payé'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('withholding_tax', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('amount_to_pay', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tva_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
