# Generated by Django 4.1.13 on 2025-08-21 23:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_taxable_remove_product_quantite_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='amount_to_pay',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_ht',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_ttc',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_tva',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='withholding_tax',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
