# Generated by Django 4.1.13 on 2025-08-26 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_purchaseorder_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bon de commande', 'verbose_name_plural': 'Bons de commande'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderproduct',
            options={'verbose_name': 'Article de commande', 'verbose_name_plural': 'Articles de commande'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('GOODS', 'Marchandises/Équipements'), ('SERVICES', 'Services'), ('WORKS', 'Travaux'), ('SUBSCRIPTION', 'Abonnement'), ('INSURANCE', 'Assurance'), ('LEASING', 'Leasing'), ('FEES', 'Honoraires'), ('RENT', 'Loyers'), ('COMMISSION', 'Commissions')], default='GOODS', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_ht',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_ttc',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_tva',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='withholding_exclusion_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='withholding_tax_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='withholding_tax_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
    ]
