# Generated by Django 4.1.13 on 2025-08-21 23:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_taxable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='product',
            name='remise',
        ),
        migrations.AlterField(
            model_name='product',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
