# Generated by Django 4.1.13 on 2025-08-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_taxable_remove_product_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prix_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
