# Generated by Django 4.1.13 on 2025-08-23 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dénomination sociale')),
                ('company_type', models.CharField(choices=[('SARL', 'SARL (Société à Responsabilité Limitée)'), ('SA', 'SA (Société Anonyme)'), ('SNC', 'SNC (Société en Nom Collectif)'), ('SCS', 'SCS (Société en Commandite Simple)'), ('SCA', 'SCA (Société en Commandite par Actions)'), ('SUARL', 'SUARL (Société Unipersonnelle à Responsabilité Limitée)'), ('EURL', 'EURL (Entreprise Unipersonnelle à Responsabilité Limitée)'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de société')),
                ('tax_identification', models.CharField(max_length=50, unique=True, verbose_name='Matricule Fiscal')),
                ('trade_register', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registre de Commerce')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('founding_date', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital social')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la banque')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de compte')),
                ('bank_rib', models.CharField(blank=True, max_length=100, null=True, verbose_name='RIB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Information de l'entreprise",
                'verbose_name_plural': "Informations de l'entreprise",
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('STATUTES', 'Statuts de la société'), ('TAX_CERTIFICATE', 'Attestation fiscale'), ('TRADE_REGISTER', 'Extrait registre de commerce'), ('IDENTITY', 'Pièce d identité du gérant'), ('OTHER', 'Autre document')], max_length=20, verbose_name='Type de document')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('file', models.FileField(upload_to='company/documents/%Y/%m/%d/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.companyinfo')),
            ],
            options={
                'verbose_name': "Document de l'entreprise",
                'verbose_name_plural': "Documents de l'entreprise",
            },
        ),
    ]
