# Generated by Django 4.1.13 on 2025-08-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
    ]
