# Generated by Django 4.1.13 on 2025-08-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_purchaseorder_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithholdingTaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_liberatory', models.BooleanField(default=False)),
                ('is_definitive', models.BooleanField(default=False)),
                ('applies_to_client_types', models.CharField(max_length=200)),
                ('minimum_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithholdingTaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('payment_date', models.DateField()),
                ('is_paid_to_treasury', models.BooleanField(default=False)),
                ('treasury_payment_ref', models.CharField(blank=True, max_length=100)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.withholdingtaxtype')),
            ],
        ),
    ]
