# Generated by Django 4.1.13 on 2025-08-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('repair', 'Needs Repair'), ('broken', 'Broken')], default='good', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
