# Generated by Django 4.1.13 on 2025-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('tax_identification', models.CharField(blank=True, max_length=50)),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Particulier'), ('COMPANY', 'Entreprise'), ('GOVERNMENT', 'Etat/Collectivité locale'), ('PUBLIC_ENTITY', 'Entreprise/Organisme public'), ('NON_RESIDENT', 'Non-résident')], max_length=20)),
                ('tax_regime', models.CharField(blank=True, choices=[('REAL', 'Régime réel'), ('SIMPLIFIED', 'Régime simplifié'), ('EXEMPT', 'Exonéré')], max_length=20)),
                ('is_resident', models.BooleanField(default=True)),
                ('is_vat_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
