# Generated by Django 4.1.13 on 2025-08-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='matricule',
        ),
    ]
