# Generated by Django 4.1.13 on 2025-08-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='notes',
        ),
    ]
